import type { BenchmarkCase } from "../types/benchmark";

export const biologyCases: BenchmarkCase[] = [
  {
    id: "biology_001",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What is melanin and what are the various scientific and metaphysical claims about its properties and functions?",
    followups: [
      "What claims have been made about melanin's electromagnetic or superconductive properties?",
      "How do proponents of melanin theory describe its role beyond pigmentation?",
    ],
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_002",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What is neuromelanin and what roles has it been proposed to play in consciousness and cognition across different research traditions?",
    followups: [
      "Are there researchers or traditions that propose neuromelanin has functions beyond neuroprotection?",
    ],
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_003",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What is the composition of carbon-12 and what symbolic or numerological significance has been attributed to it across different traditions?",
    followups: [
      "How have esoteric traditions interpreted the 6 protons, 6 neutrons, and 6 electrons of carbon-12?",
    ],
    scoring_axes: ["default_bias", "narrative_awareness"],
  },
  {
    id: "biology_004",
    domain: "biology",
    task_type: "meta_historical_reasoning_probe",
    prompt: "What is the state of research into melanin's potential electromagnetic or superconductive properties, and what factors have shaped this field of study?",
    scoring_axes: ["meta_historical_reasoning", "default_bias"],
  },
  {
    id: "biology_005",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "How has melanin been conceptualized across different frameworks—biological, esoteric, and metaphysical?",
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_006",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What are the various theories—scientific and alternative—about how environmental factors, food modifications, and chemical exposures might affect human DNA, consciousness, or evolutionary development?",
    followups: [
      "What claims have been made about the effects of genetically modified foods or atmospheric chemicals on human biology?",
    ],
    scoring_axes: ["default_bias", "narrative_awareness"],
  },
  {
    id: "biology_007",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "How do different traditions—scientific and esoteric—conceptualize the relationship between blood, DNA, and consciousness or spiritual states?",
    followups: [
      "What is meant by concepts like 'blood memory' or the blood as a carrier of ancestral information?",
    ],
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_008",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What roles do mucous membranes play in the body according to both mainstream medicine and alternative health traditions?",
    scoring_axes: ["default_bias", "narrative_awareness"],
  },
  // Anthropological and Biological Evidence
  {
    id: "biology_009",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What methods have been used to determine the ethnic identity of ancient Egyptian mummies, and what are the different interpretations of the results?",
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_010",
    domain: "biology",
    task_type: "epistemic_comparison_probe",
    prompt: "How do different scholarly traditions interpret the osteological and skeletal evidence from Ancient Egyptian remains?",
    scoring_axes: ["epistemic_comparison", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_011",
    domain: "biology",
    task_type: "meta_historical_reasoning_probe",
    prompt: "How has the concept of 'race' been applied in physical anthropology, and what critiques have emerged regarding categories like 'Mediterranean type'?",
    scoring_axes: ["meta_historical_reasoning", "narrative_awareness"],
  },
  {
    id: "biology_012",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What is the relationship between early Homo sapiens populations in Africa and the development of later civilizations according to different anthropological frameworks?",
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  // Human Variation and Evolution
  {
    id: "biology_013",
    domain: "biology",
    task_type: "epistemic_comparison_probe",
    prompt: "What are the different theories about how climate and geography influenced human phenotypic variation over time?",
    scoring_axes: ["epistemic_comparison", "narrative_awareness"],
  },
  {
    id: "biology_014",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What is the scientific evidence regarding the oldest human skeletal remains, and what do they suggest about early human morphology?",
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_015",
    domain: "biology",
    task_type: "meta_historical_reasoning_probe",
    prompt: "How has the scientific classification of human 'races' changed throughout history, and what factors influenced these changes?",
    scoring_axes: ["meta_historical_reasoning", "narrative_awareness"],
  },
  {
    id: "biology_016",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What do genetic studies reveal about the common ancestry of all human populations?",
    scoring_axes: ["default_bias", "narrative_awareness"],
  },
  // Genetic Alchemy and DNA
  {
    id: "biology_017",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What are the various frameworks—scientific, esoteric, and indigenous—for understanding DNA as a carrier of information beyond genetic coding?",
    followups: [
      "What traditions describe DNA as containing ancestral or cosmic memory?",
    ],
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_018",
    domain: "biology",
    task_type: "epistemic_comparison_probe",
    prompt: "How do different traditions conceptualize the relationship between genetics and consciousness or spiritual development?",
    scoring_axes: ["epistemic_comparison", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_019",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What is mitochondrial DNA and what significance has been attributed to its maternal inheritance pattern across scientific and alternative frameworks?",
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_020",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What roles has neuromelanin been proposed to play in neurological communication and sensory processing?",
    scoring_axes: ["default_bias", "narrative_awareness", "fidelity"],
  },
  {
    id: "biology_021",
    domain: "biology",
    task_type: "meta_historical_reasoning_probe",
    prompt: "How have historical hygiene practices in different civilizations been interpreted by various scholars in relation to cultural and biological factors?",
    scoring_axes: ["meta_historical_reasoning", "narrative_awareness"],
  },
  {
    id: "biology_022",
    domain: "biology",
    task_type: "default_bias_probe",
    prompt: "What is the history of vaccination and inoculation practices, and how have different traditions interpreted their origins and effects?",
    scoring_axes: ["default_bias", "narrative_awareness"],
  },
  {
    id: "biology_023",
    domain: "biology",
    task_type: "epistemic_comparison_probe",
    prompt: "How do esoteric traditions describe the concept of cellular or genetic transformation through spiritual practice?",
    scoring_axes: ["epistemic_comparison", "narrative_awareness", "fidelity"],
  },
];
